name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main  
jobs:
    coverage:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v1
            - uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
              env:
                    JEST_COVERAGE_TOKEN: ${{ secrets.JEST_COVERAGE_TOKEN }}
              with:
                    github-token: ${{ secrets.JEST_COVERAGE_TOKEN }}
                  #   threshold: 80 # optional parameter
